### ISSUE TITLE
Verbindung mit Heim W-lan nicht möglich

### ISSUE THREAD

**Issue by Ladeklotz** [janitz/Bascetta_Star#5]
Ich  kann mich mit dem Stern W-lan verbinden und die Seite des Sterns öffnen. Sobald ich aber die Setup Page öffnen werde ich vom Stern W-lan getrennt, das gleiche passiert wenn ich die Seite neu Lade. Zusätlich werden mir nicht die verfügbaren Netze angezeigt und wenn ich auf "Set" oder "Restart" klicke passiert nichts.

**Comment by janitz** [comment]
kann es sein, dass dein handy die verbindung trennt, und sich automatisch mit deinem heim wlan verbindet, weil es über den stern kein internetzugriff hat ?

falls ja:
bei mir hat geholfen, das heim wlan aus der wlan liste im handy zu entfernen, damit es sich nicht mehr automatisch verbinden kann

**Comment by janitz** [comment]
die liste wird erst beim neu laden angezeigt, aber da ist deine verbindung ja schon weg.
set erfordert, dass du in die eingabefelder ssid und password etwas eingetragen hast (die liste ist nur ein einfacherer weg, die ssid ins eingabefeld zu schreiben, jedoch nicht unbedingt nötig wenn du den namen deines heim wlan kennst).
restart startet das esp8266 neu und versucht dabei die (mit set) eigestellte wlan verbindung aufzubauen

**Comment by Ladeklotz** [comment]
Ich habe schon das heim W-lan aus der Liste im Handy entfernt hat leider nicht funktioniert und was auch nicht funktioniert hat, war die W-lan SSID und das Passwort einzutragen und dann  auf "Set" und danach auf "Restart" zu klicken, da ist einfach garnichts passiert.

**Comment by janitz** [comment]
kannst du das esp8266 mit dem esplorer verbinden und während dem fehler im terminal schauen, ob es einen fehler gibt und es sich selbst neu startet?
falls das esp8266 bei dem versuch abstürtzt kannst du dann hier einen screenshot vom ausgabefenster reinstellen?

**Comment by Ladeklotz** [comment]
Wie ich schon beschrieben  habe, wird mein Handy vom Stern W-lan getrennt, wenn ich von der Stern Seite zur Setup Page wechsel. Dabei tritt der Error im nachfolgenden Screenshot auf.

![Screenshot (35)](https://user-images.githubusercontent.com/28997558/102976417-cd810280-4501-11eb-8a11-582d01c558f2.png)

**Comment by janitz** [comment]
ok das sieht aus als würde der webserver abstürzen wenn du auf die seite gehst.
habe gerade gesehen, dass die build_instructions alt sind....
ich mache heute mittag ein update der build instructions.
falls du genau nach den build_instructions gehandelt hast, dann ist mein verdacht, dass die setup.min.css und die setup.min.js dateien fehlen und es deshalb abstürtzt.
warscheinlich fehlen dann auch die save_state.lc, save_wifi.lc, state.txt, map.txt und wifi.txt

**Comment by Ladeklotz** [comment]
ich habe jetzt die fehlenden Dateien auf das esp8266 hochgeladen und jetzt hat es einwandfrei funktioniert. Nur noch eine Frage, kann ich jede Zacke unterschiedlich beleuchten, aber so das die Farbe bleibt, also nicht wie bei spiral wo sich die farbe stetig ändert?

**Comment by janitz** [comment]
aktuell kann man nicht jede zacke einzeln einstellen. die funktion kann man aber sicher noch hinzufügen.

**Comment by Ladeklotz** [comment]
okey, aber danke für deine Hilfe

**Comment by janitz** [comment]
gerne, freut mich, wenn das projekt nachgebaut wird :)
